{{- if .Values.ingress.enabled -}}
{{- if not .Values.service.enabled -}}
{{- fail "A service must be enabled for the Ingress to be exposed" -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tic-tac-toe.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tic-tac-toe.fullname" . }}
                port:
                  name: http
{{- end }}