apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}