{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
      protocol: TCP
  selector:
    {{- include "tic-tac-toe.selectorLabels" . | nindent 4 }}
{{- end }}