replicaCount: 1

image:
  repository: tic-tac-toe-ynov
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  enabled: false
  port: 80 # Port fictif car l'app n'expose rien

ingress:
  enabled: false
  host: chart-example.local

config:
  PYTHONUNBUFFERED: "1"
  APP_ENV: "production"

secret:
  DUMMY_SECRET: "super_secret_value"

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi