nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: tic-tac-toe-ynov
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  enabled: false
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  host: chart-example.local
  path: /
  pathType: Prefix

config:
  PYTHONUNBUFFERED: "1"
  APP_ENV: "production"

secret:
  DUMMY_SECRET: "super_secret_value"

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
