apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}-config
  labels:
    {{- include "tic-tac-toe.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
