apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tic-tac-toe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tic-tac-toe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tic-tac-toe.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true
          tty: true
          envFrom:
            - configMapRef:
                name: {{ include "tic-tac-toe.fullname" . }}-config
            - secretRef:
                name: {{ include "tic-tac-toe.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - cat
                - tic_tac_toe.py
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - cat
                - tic_tac_toe.py
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          {{- end }}