{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}
  labels:
    {{- include "tic-tac-toe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "tic-tac-toe.selectorLabels" . | nindent 4 }}
{{- end -}}
